### ISSUE TITLE
How to allow for using local fonts?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/icfp2#1]
I've been playing around a bit, but can't figure out how to make it use the local fonts I want... more to come...

**Comment by bjornmeansbear** [comment]
`(node:9647) UnhandledPromiseRejectionWarning: Error: Font familiy not registered: Oswald. Please register it calling Font.register() method.`

Struggling with what this Font.register() thing is and how to get it to look for local font files...

**Comment by webmasterkai** [comment]
I think you figured this one out.

**Comment by bjornmeansbear** [comment]
That one was a hold over from the react to pdf
