### ISSUE TITLE
Is it possible to get an overview that is filtered by a specific track?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/icfp2#12]
I need the following tracks "overviews" (any sessions, posters, panels, whatever that might have one of the following as an assigned track)

- Returns on investment in family planning and the demographic dividend
- Sexual and reproductive health and rights among adolescents and youth
- The Faith and family planning

So, either as 3 new links added to the root app page — one per track?

**Comment by webmasterkai** [comment]
`returnsInvestmentFamilyPlanningDemographicDividend`, `sexualReproductiveHealthRightsAmongAdolescentsYouth`, `faithFamilyPlanning`
