### ISSUE TITLE
need isModerator to replace isChair in Author.jsx

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/icfp2#22]
Just like how isPresenter works, please reconfigure isModerator

**Comment by webmasterkai** [comment]
For example view http://localhost:3000/authors and search for `Rachel Cornellia`. You will see `<span style="font-style: italic;">15.4.F1.</span>`. This is created by line 25 of Author.jsx ` if (isChair) return { fontStyle: 'italic' }`
