### ISSUE TITLE
sort posters by newly showing sessionCodes they've inputted

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/icfp2#26]
its confusing but 1.1 is supposed to be 1.100, they don't have any way to keep the extra zeroes on the end on their end apparently — 1.01 = 1.010

1.001 is first, and so on

does that make sense?

**Comment by webmasterkai** [comment]
I can do this, but where? I don't see any items with `sessionType: "Poster"` that also have `sessionCode` values.

**Comment by bjornmeansbear** [comment]
poster's have an `id` inside of `presentation`
